### ISSUE TITLE
unify sources

### ISSUE THREAD

**Issue by mikedewar** [nytlabs/st-core#215]
currently, we have two different types of "source":
* in memory stores (value, list, keyvalue, pq)
* interfaces to external things (NSQ, websocket) 

They distinguish themselves as the stores need locking but no parameters, whereas the interfaces need parameters but no locking. 

The PQ is maybe a bit inbetween, as the ordering of the messages (high first or low first) could be set as a parameter. 

The NSQ and Websocket sources also explore two different ways of dealing with params. The NSQ source explicity has params set on it by selecting the source and entering in values, whereas the websocket is explicitly dialled using a connection block. 

This issue proposes two things:
 1. stores and interfaces ought to be different types. They should be rendered differently in the UI, locking logic should be different, and their method vocab should be different. 
 2. for interfaces, we should ditch parameter setting in favour of connection blocks.

**Comment by nikhan** [comment]
I agree. does this mean:
- NSQ should get a 'connect' block?
- locking only applies to stores and not interfaces?

**Comment by mikedewar** [comment]
yes and yes.

**Comment by mikedewar** [comment]
further, each interface (esp. now that we've ditched `server`) should literally have `connect`, `receive`, and `send` blocks. If we can figure it out, I'd love it if the `send` and `receive` blocks were common.

**Comment by mikedewar** [comment]
I think this has been thoroughly explored now. Closing.
