### ISSUE TITLE
API groups proposal

### ISSUE THREAD

**Issue by mikedewar** [nytlabs/st-core#23]
* A Group is a collection of Blocks and other Groups.
* A Group does not have to belong to an existing Group.
* A Block does have to belong to an existing Group.
* There is always a top-level Group with id 0 which acts as a Block's default Group.
* A Group is for organisational purposes only.
* Groups and Blocks are collectively called Nodes.
* A Group knows what it contains - it knows its child Nodes.
* A Node doesn't know who its parent is.

Code is here:
https://github.com/mikedewar/st-core/blob/master/thinking/api/main.go

The following test code:
```
curl localhost:7071/block -d'{"name":"A"}'
curl localhost:7071/block -d'{"name":"B"}'
curl localhost:7071/block -d'{"name":"C"}'
printf "\n"
printf "\n"
curl localhost:7071
printf "\n"
curl localhost:7071/group -d'{"ParentID":0, "ChildIDs":[1,2]}'
printf "\n"
printf "\n"
curl localhost:7071
```
returns
```
OKOKOK

0 -
  1
  2
  3

OK

0 -
  4-
    1
    2
  3
```

**Comment by nikhan** [comment]
we did it! :sake:
