### ISSUE TITLE
Priority Queue Proposal

### ISSUE THREAD

**Issue by mikedewar** [nytlabs/st-core#52]
This is to suggest how priority queues - an important language construct for dealing with streaming data - should appear in the language. 

A priority queue is a store - and will live in memory in `core`. 

Highest priority is the lowest number in the queue. 

It will have associated blocks:
* pqPush - add an entry with a supplied time to the queue
* pqPop - remove the highest priority element
* pqPeek - look at the highest priority element without removing it

Sample patterns to come below.

**Comment by mikedewar** [comment]
![untitled drawing](https://cloud.githubusercontent.com/assets/149211/6215307/4825f84e-b5cd-11e4-9833-1997c9cf1f1f.png)

**Comment by nikhan** [comment]
s/Pop/shift/

**Comment by nikhan** [comment]
looks good, I'm assuming that the pqPush is going to have two inputs, something like [msg] and [priority] where [priority] is always an int
